name: Build Golang

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Golang
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - name: Display Go versions
        run: go version
      - name: Install dependecies
        run: go get .
      - name: Run tests
        run: go test ./...
      - name: Build binary
        run: go build -o lecture-cicd-go-app ./main.go

